# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: target
  displayName: Target Database
  type: string
  default: flyway_test
  values:
    - flyway_test
    - flyway_qc
    - flyway_stage
    - flyway_prod

variables:
- name: targetDb
  value: ${{ parameters.target }}

trigger:
- none

pool:
  name: Flyway

steps:

- script: |
    /tools/flyway/flyway -url=jdbc:sqlserver://localhost:1434;databaseName=$(targetDb);encrypt=false;integratedSecurity=true;trustServerCertificate=true -outOfOrder=false migrate
  displayName: 'Run Flyway migrations'

#- task: CmdLine@2
#  inputs:
#    script: |      
#      /tools/flyway/flyway -url=jdbc:sqlserver://localhost:1434;databaseName=$(targetDb);encrypt=false;integratedSecurity=true;trustServerCertificate=true -outOfOrder=false migrate
#  displayName: 'Run Flyway migrations'
  

