# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  inputs:
    script: |
      dir
      
      \tools\flyway\flyway -url=jdbc:sqlserver://localhost:1434;databaseName=flyway_qc;encrypt=false;integratedSecurity=true;trustServerCertificate=true -outOfOrder=false migrate
  displayName: 'Run a multi-line script'
  

